import type { Spot } from "./types";

export const MOCK_SPOTS: Spot[] = [
  {
    id: 1,
    lat: 37.498095,
    lng: 127.02761,
    address: "서울 강남구 강남대로",
    name: "강남역 3번 출구 흡연구역",
    amenities: { ashtray: true, chair: false, roof: false, size: "small" },
    isOfficial: true,
    source: "public_data",
    status: "active",
    smokerScore: 10,
    residentScore: -2,
    positiveCount: 6,
    complaintCount: 1,
  },
  {
    id: 2,
    lat: 37.5013,
    lng: 127.0396,
    address: "서울 강남구 삼성동",
    name: "코엑스 후문 흡연장",
    amenities: { ashtray: true, chair: true, roof: true, size: "large" },
    isOfficial: true,
    source: "public_data",
    status: "active",
    smokerScore: 14,
    residentScore: -1,
    positiveCount: 8,
    complaintCount: 1,
  },
  {
    id: 3,
    lat: 37.5665,
    lng: 126.978,
    address: "서울 중구 세종대로",
    name: "시청 뒷골목",
    amenities: { ashtray: false, chair: false, roof: false, size: "small" },
    isOfficial: false,
    source: "user",
    status: "warning",
    smokerScore: 3,
    residentScore: -3,
    positiveCount: 2,
    complaintCount: 3,
  },
  {
    id: 4,
    lat: 37.5172,
    lng: 127.0473,
    address: "서울 강남구 테헤란로",
    name: "언주역 골목",
    amenities: { ashtray: false, chair: false, roof: false, size: "small" },
    isOfficial: false,
    source: "user",
    status: "nosmoking",
    smokerScore: 1,
    residentScore: -8,
    positiveCount: 1,
    complaintCount: 5,
  },
];
